"""empty message

Revision ID: 26ef3e3ec9d1
Revises: 43a7707ec7da
Create Date: 2023-05-10 06:50:45.138550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26ef3e3ec9d1'
down_revision = '43a7707ec7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_column('num_upcoming_shows')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
