"""empty message

Revision ID: 3180c7b8df95
Revises: d29b56e6ad46
Create Date: 2023-05-02 13:16:40.251769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3180c7b8df95'
down_revision = 'd29b56e6ad46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=False))

    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('artist_image_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('venue_name', sa.String(), nullable=True))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('num_upcoming_shows')
        batch_op.drop_column('seeking_talent')

    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_column('venue_name')
        batch_op.drop_column('artist_image_link')
        batch_op.drop_column('artist_name')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###
